"use client"

import { useState } from "react"
import {
  FileText, Download, BarChart3, TrendingUp, TrendingDown, PiggyBank,
  AlertTriangle, Calendar, Filter, RefreshCw, Printer, Share2,
  ChevronDown, CreditCard, Wallet, LineChart, PieChart, Target
} from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Progress } from "@/components/ui/progress"
import { PageHeader } from "@/components/page-header"
import { useStore } from "@/lib/store"
import { formatINR, totalThisMonth, spendByCategory, computeHealthScore } from "@/lib/finance"
import { emis, investments, subscriptions } from "@/lib/mock-data"

function downloadReport(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/plain" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

const monthlyData = [
  { month: "Jan", income: 40000, expense: 31200, savings: 8800 },
  { month: "Feb", income: 40000, expense: 27800, savings: 12200 },
  { month: "Mar", income: 40000, expense: 33100, savings: 6900 },
  { month: "Apr", income: 40000, expense: 29400, savings: 10600 },
  { month: "May", income: 40000, expense: 26800, savings: 13200 },
  { month: "Jun", income: 40000, expense: 24200, savings: 15800 },
]

export default function ReportsPage() {
  const { profile, expenses } = useStore()
  const [selectedPeriod, setSelectedPeriod] = useState("June 2026")
  const [activeTab, setActiveTab] = useState<"overview" | "categories" | "tax">("overview")

  const spent = totalThisMonth(expenses)
  const saved = Math.max(0, profile.income - spent)
  const health = computeHealthScore(profile, expenses)
  const byCategory = spendByCategory(expenses)
  const totalInvested = investments.reduce((s, i) => s + i.currentValue, 0)
  const totalSubscriptions = subscriptions.reduce((s, sub) => s + sub.amount, 0)
  const totalEMI = emis.reduce((s, e) => s + e.emi, 0)
  const netWorth = totalInvested + profile.savings - profile.loans

  const now = new Date()
  const monthName = now.toLocaleDateString("en-IN", { month: "long", year: "numeric" })

  function generateMonthlyReport() {
    const lines = [
      `============================================`,
      `  SMARTBUDGET AI — MONTHLY FINANCIAL REPORT`,
      `  ${monthName}`,
      `============================================`,
      ``,
      `NAME       : ${profile.name}`,
      `PERSONA    : ${profile.persona}`,
      `OCCUPATION : ${profile.occupation}`,
      ``,
      `--- INCOME & SPENDING ---`,
      `Monthly Income    : ${formatINR(profile.income)}`,
      `Total Spent       : ${formatINR(spent)}`,
      `Saved This Month  : ${formatINR(saved)}`,
      `Savings Rate      : ${Math.round((saved / profile.income) * 100)}%`,
      ``,
      `--- LOANS & EMIs ---`,
      `Total Monthly EMI : ${formatINR(totalEMI)}`,
      ...emis.map((e) => `  ${e.name.padEnd(20)} : ${formatINR(e.emi)}/mo  (Remaining: ${formatINR(e.remaining)})`),
      ``,
      `--- SUBSCRIPTIONS ---`,
      `Monthly Sub Cost  : ${formatINR(totalSubscriptions)}`,
      ...subscriptions.map((s) => `  ${s.name.padEnd(20)} : ${formatINR(s.amount)}/mo  [${s.status}]`),
      ``,
      `--- INVESTMENTS ---`,
      `Portfolio Value   : ${formatINR(totalInvested)}`,
      ...investments.map((i) => `  ${i.name.padEnd(30)} : ${formatINR(i.currentValue)}  (${i.returns}% returns)`),
      ``,
      `--- SPENDING BY CATEGORY ---`,
      ...byCategory.map((c) => `  ${c.category.padEnd(18)} : ${formatINR(c.amount)}`),
      ``,
      `--- FINANCIAL HEALTH SCORE ---`,
      `Health Score : ${health.score}/100`,
      ...health.parts.map((p) => `  ${p.label.padEnd(20)} : ${p.value}/${p.max}`),
      ``,
      `============================================`,
      `  Generated by SmartBudget AI on ${new Date().toLocaleString("en-IN")}`,
      `============================================`,
    ]
    downloadReport(lines.join("\n"), `smartbudget-report-${monthName.replace(" ", "-")}.txt`)
  }

  function generateTaxSummary() {
    const lines = [
      `============================================`,
      `  SMARTBUDGET AI — TAX SUMMARY FY 2025-26`,
      `============================================`,
      ``,
      `NAME       : ${profile.name}`,
      ``,
      `--- 80C DEDUCTIONS (up to ₹1,50,000) ---`,
      `SIP in ELSS Funds  : ${formatINR(investments.filter((i) => i.type === "Mutual Fund").reduce((s, i) => s + i.sipAmount * 12, 0))}`,
      `Provident Fund     : ₹0 (add manually)`,
      ``,
      `--- HOME LOAN (Section 24) ---`,
      `Interest Paid      : ${formatINR(emis.filter((e) => e.name.toLowerCase().includes("home")).reduce((s, e) => s + (e.remaining * e.rate) / (12 * 100) * 12, 0))}`,
      ``,
      `--- EDUCATION LOAN (Section 80E) ---`,
      `Interest Paid      : ${formatINR(emis.filter((e) => e.name.toLowerCase().includes("education")).reduce((s, e) => s + (e.remaining * e.rate) / (12 * 100) * 12, 0))}`,
      ``,
      `NOTE: This is an estimate. Consult a CA for accurate filing.`,
      `============================================`,
    ]
    downloadReport(lines.join("\n"), `smartbudget-tax-summary-2025-26.txt`)
  }

  return (
    <div className="space-y-6 p-5 md:p-8">
      <PageHeader
        title="Financial Reports"
        description="Generate monthly summaries, tax reports, and net worth statements. Download, share, or print your complete financial picture."
        action={
          <div className="flex items-center gap-2">
            <Badge variant="secondary" className="gap-1.5 text-sm px-3 py-1.5">
              <FileText className="size-4" /> {monthName}
            </Badge>
          </div>
        }
      />

      {/* Key Metrics */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardContent className="p-5">
            <div className="flex items-center justify-between">
              <p className="text-sm text-muted-foreground">Monthly Income</p>
              <Wallet className="size-4 text-muted-foreground" />
            </div>
            <p className="mt-2 text-2xl font-bold tabular-nums">{formatINR(profile.income)}</p>
            <p className="mt-1 text-xs text-muted-foreground">Fixed salary</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-5">
            <div className="flex items-center justify-between">
              <p className="text-sm text-muted-foreground">Spent This Month</p>
              <TrendingDown className="size-4 text-destructive" />
            </div>
            <p className="mt-2 text-2xl font-bold tabular-nums text-destructive">{formatINR(spent)}</p>
            <p className="mt-1 text-xs text-muted-foreground">{Math.round((spent / profile.income) * 100)}% of income</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-5">
            <div className="flex items-center justify-between">
              <p className="text-sm text-muted-foreground">Saved This Month</p>
              <PiggyBank className="size-4 text-primary" />
            </div>
            <p className="mt-2 text-2xl font-bold tabular-nums text-primary">{formatINR(saved)}</p>
            <p className="mt-1 text-xs text-muted-foreground">{Math.round((saved / profile.income) * 100)}% savings rate</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-5">
            <div className="flex items-center justify-between">
              <p className="text-sm text-muted-foreground">Net Worth</p>
              <TrendingUp className="size-4 text-primary" />
            </div>
            <p className="mt-2 text-2xl font-bold tabular-nums text-primary">{formatINR(netWorth)}</p>
            <p className="mt-1 text-xs text-muted-foreground">Assets minus liabilities</p>
          </CardContent>
        </Card>
      </div>

      {/* Tab Navigation */}
      <div className="flex gap-1 rounded-xl bg-muted p-1">
        {(["overview", "categories", "tax"] as const).map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`flex-1 rounded-lg px-3 py-2 text-sm font-medium capitalize transition-all ${
              activeTab === tab
                ? "bg-card text-foreground shadow-sm"
                : "text-muted-foreground hover:text-foreground"
            }`}
          >
            {tab === "overview" ? "📊 Overview" : tab === "categories" ? "🏷️ Categories" : "🧾 Tax"}
          </button>
        ))}
      </div>

      {/* Overview Tab */}
      {activeTab === "overview" && (
        <div className="space-y-4">
          {/* 6-Month Income vs Expense Bar Chart (visual) */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <BarChart3 className="size-5 text-primary" /> 6-Month Income vs Expense Trend
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-end gap-3 h-48">
                {monthlyData.map((m) => {
                  const expPct = (m.expense / m.income) * 100
                  const savPct = (m.savings / m.income) * 100
                  const isCurrent = m.month === "Jun"
                  return (
                    <div key={m.month} className="flex flex-1 flex-col items-center gap-2">
                      <div className="relative flex w-full flex-col justify-end" style={{ height: "160px" }}>
                        {/* Income bar (background) */}
                        <div className="absolute inset-0 rounded-lg bg-muted" />
                        {/* Expense bar */}
                        <div
                          className={`absolute bottom-0 left-0 right-0 rounded-lg transition-all ${isCurrent ? "bg-primary" : "bg-primary/40"}`}
                          style={{ height: `${expPct}%` }}
                        />
                        {/* Savings indicator */}
                        <div
                          className="absolute bottom-0 left-0 right-0 rounded-lg bg-destructive/60"
                          style={{ height: `${expPct}%`, opacity: 0.7 }}
                        />
                        <div
                          className={`absolute bottom-0 left-0 right-0 rounded-lg ${isCurrent ? "bg-primary" : "bg-blue-400/60"}`}
                          style={{ height: `${expPct}%` }}
                        />
                      </div>
                      <span className={`text-xs font-medium ${isCurrent ? "text-primary" : "text-muted-foreground"}`}>{m.month}</span>
                      {isCurrent && <div className="w-1.5 h-1.5 rounded-full bg-primary" />}
                    </div>
                  )
                })}
              </div>

              {/* Legend + data table */}
              <div className="mt-4 overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-border">
                      <th className="py-2 text-left font-medium text-muted-foreground">Month</th>
                      <th className="py-2 text-right font-medium text-muted-foreground">Expense</th>
                      <th className="py-2 text-right font-medium text-muted-foreground">Saved</th>
                      <th className="py-2 text-right font-medium text-muted-foreground">Rate</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border">
                    {monthlyData.map((m) => (
                      <tr key={m.month} className={m.month === "Jun" ? "bg-primary/5 font-semibold" : ""}>
                        <td className="py-2">{m.month}</td>
                        <td className="py-2 text-right tabular-nums text-destructive">{formatINR(m.expense)}</td>
                        <td className="py-2 text-right tabular-nums text-primary">{formatINR(m.savings)}</td>
                        <td className="py-2 text-right tabular-nums">{Math.round((m.savings / m.income) * 100)}%</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>

          {/* Health Score */}
          <Card className="border-primary/20 bg-primary/5">
            <CardContent className="flex items-center justify-between p-5">
              <div>
                <p className="font-semibold">Financial Health Score</p>
                <p className="text-sm text-muted-foreground">Based on savings, debt, investments & discipline</p>
                <div className="mt-3 space-y-2">
                  {health.parts.map((p) => (
                    <div key={p.label} className="flex items-center gap-2 text-sm">
                      <span className="w-32 text-muted-foreground text-xs">{p.label}</span>
                      <div className="flex-1 h-1.5 rounded-full bg-muted overflow-hidden">
                        <div className="h-full rounded-full bg-primary" style={{ width: `${(p.value / p.max) * 100}%` }} />
                      </div>
                      <span className="w-12 text-right text-xs font-medium">{p.value}/{p.max}</span>
                    </div>
                  ))}
                </div>
              </div>
              <div className="text-right ml-6">
                <p className="text-6xl font-black text-primary">{health.score}</p>
                <p className="text-sm text-muted-foreground">/ 100</p>
              </div>
            </CardContent>
          </Card>

          {/* Quick Stats */}
          <div className="grid gap-4 sm:grid-cols-3">
            <Card>
              <CardContent className="p-5">
                <p className="text-sm text-muted-foreground flex items-center gap-1.5"><CreditCard className="size-4" /> Total EMI/month</p>
                <p className="mt-1 text-xl font-bold tabular-nums text-destructive">{formatINR(totalEMI)}</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-5">
                <p className="text-sm text-muted-foreground flex items-center gap-1.5"><RefreshCw className="size-4" /> Subscriptions</p>
                <p className="mt-1 text-xl font-bold tabular-nums">{formatINR(totalSubscriptions)}/mo</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-5">
                <p className="text-sm text-muted-foreground flex items-center gap-1.5"><TrendingUp className="size-4" /> Portfolio</p>
                <p className="mt-1 text-xl font-bold tabular-nums text-primary">{formatINR(totalInvested)}</p>
              </CardContent>
            </Card>
          </div>
        </div>
      )}

      {/* Categories Tab */}
      {activeTab === "categories" && (
        <div className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <PieChart className="size-5 text-primary" /> Spending by Category — {monthName}
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {byCategory.map((c, idx) => {
                const pct = spent > 0 ? Math.round((c.amount / spent) * 100) : 0
                const colors = [
                  "bg-blue-500", "bg-purple-500", "bg-orange-500", "bg-green-500",
                  "bg-pink-500", "bg-yellow-500", "bg-cyan-500"
                ]
                return (
                  <div key={c.category}>
                    <div className="mb-1.5 flex justify-between text-sm">
                      <div className="flex items-center gap-2">
                        <div className={`size-3 rounded-full ${colors[idx % colors.length]}`} />
                        <span className="font-medium">{c.category}</span>
                      </div>
                      <span className="font-medium tabular-nums">
                        {formatINR(c.amount)} <span className="text-muted-foreground text-xs">({pct}%)</span>
                      </span>
                    </div>
                    <div className="h-2 w-full overflow-hidden rounded-full bg-muted">
                      <div className={`h-full rounded-full ${colors[idx % colors.length]}`} style={{ width: `${pct}%` }} />
                    </div>
                  </div>
                )
              })}
              {byCategory.length === 0 && (
                <p className="py-8 text-center text-sm text-muted-foreground">No expenses logged yet this month.</p>
              )}
            </CardContent>
          </Card>

          {/* Category Comparison */}
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Month vs Average Comparison</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {[
                  { cat: "Food & Dining", current: 3070, avg: 2190, icon: "🍔" },
                  { cat: "Transport", current: 680, avg: 820, icon: "🚗" },
                  { cat: "Entertainment", current: 700, avg: 950, icon: "🎬" },
                  { cat: "Shopping", current: 1899, avg: 1400, icon: "🛍️" },
                  { cat: "Bills & Utilities", current: 2249, avg: 2300, icon: "⚡" },
                ].map((row) => {
                  const diff = row.current - row.avg
                  const isOver = diff > 0
                  return (
                    <div key={row.cat} className="flex items-center gap-4">
                      <span className="text-xl w-8">{row.icon}</span>
                      <div className="flex-1 min-w-0">
                        <div className="flex justify-between text-sm mb-1">
                          <span className="font-medium">{row.cat}</span>
                          <span className={`font-medium tabular-nums ${isOver ? "text-destructive" : "text-primary"}`}>
                            {isOver ? "+" : ""}{formatINR(diff)}
                          </span>
                        </div>
                        <div className="flex gap-1 h-2">
                          <div className="flex-1 rounded-full overflow-hidden bg-muted">
                            <div className="h-full bg-muted-foreground/40" style={{ width: `${(row.avg / 3500) * 100}%` }} />
                          </div>
                          <div className="flex-1 rounded-full overflow-hidden bg-muted">
                            <div className={`h-full ${isOver ? "bg-destructive" : "bg-primary"}`} style={{ width: `${(row.current / 3500) * 100}%` }} />
                          </div>
                        </div>
                        <div className="flex justify-between text-[10px] text-muted-foreground mt-0.5">
                          <span>Avg: {formatINR(row.avg)}</span>
                          <span>This month: {formatINR(row.current)}</span>
                        </div>
                      </div>
                    </div>
                  )
                })}
              </div>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Tax Tab */}
      {activeTab === "tax" && (
        <div className="space-y-4">
          <Card className="border-yellow-500/20 bg-yellow-50/50 dark:bg-yellow-500/5">
            <CardContent className="flex items-start gap-3 p-5">
              <AlertTriangle className="mt-0.5 size-5 shrink-0 text-yellow-600" />
              <div>
                <p className="font-semibold text-yellow-700 dark:text-yellow-400">Tax Saving Opportunity</p>
                <p className="mt-0.5 text-sm text-muted-foreground">
                  Your SIP investments qualify for Section 80C deductions (up to ₹1,50,000). Education loan interest is deductible under Section 80E with no upper limit.
                  Consider investing more in ELSS funds before March to maximise deductions.
                </p>
              </div>
            </CardContent>
          </Card>

          <div className="grid gap-4 sm:grid-cols-2">
            {[
              {
                section: "Section 80C",
                limit: 150000,
                used: investments.filter((i) => i.type === "Mutual Fund").reduce((s, i) => s + i.sipAmount * 12, 0),
                items: ["ELSS SIP", "Provident Fund", "Life Insurance"],
                color: "text-primary",
              },
              {
                section: "Section 80E",
                limit: Infinity,
                used: emis.filter((e) => e.name.toLowerCase().includes("education")).reduce((s, e) => s + Math.round((e.remaining * e.rate) / (12 * 100) * 12), 0),
                items: ["Education Loan Interest"],
                color: "text-blue-600",
              },
            ].map((sec) => (
              <Card key={sec.section}>
                <CardContent className="p-5 space-y-3">
                  <div>
                    <p className="font-bold">{sec.section}</p>
                    <p className="text-sm text-muted-foreground">
                      {sec.limit === Infinity ? "No upper limit" : `Limit: ${formatINR(sec.limit)}`}
                    </p>
                  </div>
                  <div>
                    <div className="mb-1 flex justify-between text-sm">
                      <span className="text-muted-foreground">Utilized</span>
                      <span className={`font-bold ${sec.color}`}>{formatINR(sec.used)}</span>
                    </div>
                    {sec.limit !== Infinity && (
                      <Progress value={(sec.used / sec.limit) * 100} className="h-2" />
                    )}
                  </div>
                  <ul className="space-y-1">
                    {sec.items.map((item) => (
                      <li key={item} className="flex items-center gap-2 text-sm text-muted-foreground">
                        <div className="size-1.5 rounded-full bg-muted-foreground" />
                        {item}
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      )}

      {/* Download Buttons */}
      <div className="grid gap-4 sm:grid-cols-3">
        <Card>
          <CardContent className="p-5">
            <p className="font-semibold">Monthly Report</p>
            <p className="mt-1 text-sm text-muted-foreground">
              Full income, expense, EMI, subscription, and health score for {monthName}.
            </p>
            <Button className="mt-4 w-full" onClick={generateMonthlyReport}>
              <Download className="size-4" /> Download Report
            </Button>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-5">
            <p className="font-semibold">Tax Summary (FY 2025–26)</p>
            <p className="mt-1 text-sm text-muted-foreground">
              80C, 80E deductions and home loan interest. Share with your CA.
            </p>
            <Button className="mt-4 w-full" variant="outline" onClick={generateTaxSummary}>
              <Download className="size-4" /> Tax Summary
            </Button>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-5">
            <p className="font-semibold">Net Worth Statement</p>
            <p className="mt-1 text-sm text-muted-foreground">
              Assets, liabilities, and investment portfolio snapshot.
            </p>
            <Button className="mt-4 w-full" variant="outline" onClick={() => {
              const lines = [
                `NET WORTH STATEMENT — ${monthName}`,
                ``,
                `ASSETS`,
                `Portfolio Value : ${formatINR(totalInvested)}`,
                `Savings Account : ${formatINR(profile.savings)}`,
                ``,
                `LIABILITIES`,
                `Total Loans     : ${formatINR(profile.loans)}`,
                ``,
                `NET WORTH : ${formatINR(netWorth)}`,
              ]
              downloadReport(lines.join("\n"), `net-worth-${monthName}.txt`)
            }}>
              <Download className="size-4" /> Net Worth
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
